# Generated by Django 5.2.17 on 2026-09-21 19:44

import django.db.models.deletion
import questoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Assunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assuntos",
                        to="questoes.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assunto",
                "verbose_name_plural": "Assuntos",
                "ordering": ["disciplina__nome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        default="medio",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_revisao", "Em revisão"),
                            ("aprovada", "Aprovada"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("banca", models.CharField(blank=True, max_length=100)),
                ("ano", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "assunto",
                    models.ForeignKey(
                        help_text="O módulo/assunto ao qual esta questão pertence. A disciplina vem automaticamente dele.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questoes",
                        to="questoes.assunto",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ImagemQuestao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.ImageField(upload_to=questoes.models.caminho_imagem_questao),
                ),
                ("legenda", models.CharField(blank=True, max_length=255)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="questoes.questao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da questão",
                "verbose_name_plural": "Imagens da questão",
                "ordering": ["enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letra", models.CharField(max_length=1)),
                ("texto", models.TextField()),
                ("correta", models.BooleanField(default=False)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="questoes.questao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "ordering": ["letra"],
            },
        ),
        migrations.AddConstraint(
            model_name="assunto",
            constraint=models.UniqueConstraint(
                fields=("disciplina", "nome"), name="assunto_unico_por_disciplina"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternativa",
            constraint=models.UniqueConstraint(
                fields=("questao", "letra"), name="letra_unica_por_questao"
            ),
        ),
    ]
