# Generated by hand (não pelo makemigrations) para poder fazer a
# migração de dados no meio do caminho: cria o modelo Frente, encaixa
# Assunto embaixo dela (em vez de Disciplina direto) e preenche os
# dados de quem já existir antes de travar os campos como obrigatórios.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# As 7 disciplinas do cursinho e o nome de cada uma das suas duas
# frentes. Sociologia/Filosofia é o único caso em que cada frente tem
# o nome da matéria em si, em vez de "Frente A"/"Frente B" genérico.
DISCIPLINAS_E_FRENTES = [
    ("Matemática", "Frente A", "Frente B"),
    ("Geografia", "Frente A", "Frente B"),
    ("Física", "Frente A", "Frente B"),
    ("Química", "Frente A", "Frente B"),
    ("Biologia", "Frente A", "Frente B"),
    ("História", "Frente A", "Frente B"),
    ("Sociologia/Filosofia", "Sociologia", "Filosofia"),
]


def semear_disciplinas_e_frentes(apps, schema_editor):
    Disciplina = apps.get_model("questoes", "Disciplina")
    Frente = apps.get_model("questoes", "Frente")

    for nome_disciplina, nome_frente_a, nome_frente_b in DISCIPLINAS_E_FRENTES:
        disciplina, _ = Disciplina.objects.get_or_create(nome=nome_disciplina)
        Frente.objects.get_or_create(
            disciplina=disciplina, letra="A", defaults={"nome": nome_frente_a}
        )
        Frente.objects.get_or_create(
            disciplina=disciplina, letra="B", defaults={"nome": nome_frente_b}
        )


def preencher_frente_dos_assuntos_existentes(apps, schema_editor):
    # Qualquer Assunto criado antes desta migração (só existiam dados de
    # teste até aqui) cai na Frente A da disciplina que já tinha, com
    # aula 1 por padrão — o professor ajusta depois pela tela de
    # planejamento ou pelo admin, se precisar.
    Assunto = apps.get_model("questoes", "Assunto")
    Frente = apps.get_model("questoes", "Frente")

    for assunto in Assunto.objects.all():
        frente_a, _ = Frente.objects.get_or_create(
            disciplina_id=assunto.disciplina_id,
            letra="A",
            defaults={"nome": "Frente A"},
        )
        assunto.frente = frente_a
        if assunto.aula is None:
            assunto.aula = 1
        assunto.save(update_fields=["frente", "aula"])


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letra",
                    models.CharField(
                        choices=[("A", "Frente A"), ("B", "Frente B")], max_length=1
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='Nome exibido para a frente. Ex: "Frente A" ou, no caso de Sociologia/Filosofia, o nome da matéria em si ("Sociologia").',
                        max_length=100,
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frentes",
                        to="questoes.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frente",
                "verbose_name_plural": "Frentes",
                "ordering": ["disciplina__nome", "letra"],
            },
        ),
        migrations.AddConstraint(
            model_name="frente",
            constraint=models.UniqueConstraint(
                fields=("disciplina", "letra"), name="frente_unica_por_disciplina"
            ),
        ),
        migrations.AddField(
            model_name="assunto",
            name="descricao",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assunto",
            name="frente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assuntos",
                to="questoes.frente",
            ),
        ),
        migrations.AddField(
            model_name="assunto",
            name="aula",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RunPython(
            semear_disciplinas_e_frentes, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            preencher_frente_dos_assuntos_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="assunto", name="assunto_unico_por_disciplina"
        ),
        migrations.AlterField(
            model_name="assunto",
            name="frente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assuntos",
                to="questoes.frente",
            ),
        ),
        migrations.AlterField(
            model_name="assunto",
            name="aula",
            field=models.PositiveSmallIntegerField(
                choices=[(i, f"Aula {i}") for i in range(1, 31)],
                help_text="A qual aula (1 a 30) este conteúdo se refere.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.RemoveField(model_name="assunto", name="disciplina"),
        migrations.AlterModelOptions(
            name="assunto",
            options={
                "ordering": ["frente__disciplina__nome", "frente__letra", "aula", "nome"],
                "verbose_name": "Assunto",
                "verbose_name_plural": "Assuntos",
            },
        ),
        migrations.AddConstraint(
            model_name="assunto",
            constraint=models.UniqueConstraint(
                fields=("frente", "nome"), name="assunto_unico_por_frente"
            ),
        ),
    ]
