# Generated by Django 5.2.17 on 2026-09-21 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0002_frente_e_aula"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="frente",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Só quem estiver aqui vê e cadastra conteúdo desta frente no painel. Coordenadores (superusuários) sempre veem todas.",
                related_name="frentes_atribuidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professores responsáveis",
            ),
        ),
    ]
