# Generated by Django 5.2.17 on 2026-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0003_frente_professores"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="autoria_propria",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questao",
            name="prova",
            field=models.CharField(
                blank=True,
                help_text='Nome/identificação da prova. Ex: "1ª fase", "2º dia".',
                max_length=150,
            ),
        ),
    ]
