# Generated by Django 5.2.17 on 2026-09-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0005_portugues_e_redacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='dificuldade',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='status',
        ),
    ]
