# Generated by Django 5.2.17 on 2026-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Deixe em branco para um evento de um dia só. Preencha para um evento que dura vários dias (ele aparece de forma contínua no calendário).', null=True),
        ),
    ]
