# Generated by Django 5.2.17 on 2026-09-23 12:35

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_data_fim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=150)),
                ('faculdade', models.CharField(blank=True, help_text='Instituição onde se formou ou está cursando.', max_length=150)),
                ('foto', models.ImageField(blank=True, help_text='Foto usada no material didático impresso.', null=True, upload_to=core.models.caminho_foto_perfil)),
                ('descricao', models.TextField(blank=True, help_text='Uma breve apresentação sua para o material.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do professor',
                'verbose_name_plural': 'Perfis dos professores',
            },
        ),
    ]
