# Generated by Django 5.2.17 on 2026-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='senha_provisoria',
            field=models.BooleanField(default=False, help_text='Marque ao criar a conta com a senha genérica — a pessoa é obrigada a cadastrar uma senha nova assim que entrar pela primeira vez.'),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='telefone',
            field=models.CharField(blank=True, help_text='Só números, com DDD. É o que o professor usa pra entrar no sistema.', max_length=20, null=True, unique=True),
        ),
    ]
